networks:
  dev:
    driver: bridge

volumes:
  db-data: {}

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastApiTest
    ports:
      - "${API_PORT:-8000}:8000"
    networks:
      - dev
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}",
        ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - dev
    restart: unless-stopped
