networks:
  dev:
    driver: bridge

volumes:
  db-data: {}

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Monster_IA_API
    env_file:
      - .env
    volumes:
      - ./app:/app
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}
      - SMTP_HOST=${MAILPIT_HOST:-mailpit}
      - SMTP_PORT=${MAILPIT_PORT:-1025}
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dev

  postgres:
    image: postgres:18-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}",
        ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - dev
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit:v1.27.9
    container_name: mailpit-dev
    ports:
      - "${MAILPIT_UI_PORT:-8025}:8025"
      - "1025:1025"
    networks:
      - dev
    restart: unless-stopped
